const Map<String, String> en_US = {
// TODO: A
'Ap_dung': 'Apply',
'app_name': "EMO EN",

// TODO: B
'Ban_co_chac_huy_hoa_don': 'Are you sure you want to delete invoice?',
'Ban_co_chac_chan_muon_xoa_khach_hang': 'Are you sure you want to delete partner',

'Bao_che_bien': '',

// TODO: C
'Chiet_khau': 'Discount',
'Chi_nhanh': 'Branch',
'Code': 'Code',
'con_trong': 'empties',
'Chi_tiet_hang_hoa': 'Product details',
'Chinh_sua': "Edit",
"Cho_phep_nhan_vien_thay_doi_gia": "Allow Staff To Change Price",
"Cho_phep_nhan_vien_thay_doi_hang_hoa": "Allow Staff To Change Product",
"Nhan_du_lieu_tu_thu_ngan_khac": "Receive Data From Other Terminal",
"Mo_cashbox_sau_thanh_toan": "Open Cashbox After Payment",
"Khong_cho_phep_ban_hang_khi_het_ton_kho":
"Don't Allow Sale When Stock Is Empty",
"Cai_dat_man_hinh_chon_sp": "Choose Product Screen Setting",
"So_the_cung": "Card Number Count",
"Thiet_lap_VAT": "VAT Configuration",
"Don_vi_tien_te": "Currency Unit",
"Am_bao_thanh_toan": "Layout Notification Ring",
"Nhan_tin_nhan/thong_bao": "Notification Pay",
"Thiet_lap_thanh_toan": "Payment Setting",
"Kich_hoat_thanh_toan_qua_QR": "Enable QR Payment",
"In_hoa_don_truoc_khi_thanh_toan_QR": "Print invoice before QR Payment",
"Thanh_toan_VNPAY": "VNPAY Payment",
"Thanh_toan_ViettelPay": "ViettelPay Payment",
"May_in_thu_ngan": "Printer Type Cashier",
"May_in_bao_bep_a": "Printer Type Kitchen A",
"May_in_bao_bep_b": "Printer Type Kitchen B",
"May_in_bao_bep_c": "Printer Type Kitchen C",
"May_in_bao_bep_d": "Printer Type Kitchen D",
"May_in_bao_pha_che_a": "Printer Type Bartender A",
"May_in_bao_pha_che_b": "Printer Type Bartender B",
"May_in_bao_pha_che_c": "Printer Type Bartender C",
"May_in_bao_pha_che_d": "Printer Type Bartender D",
"May_in_tem": "Printer Type Template",
"Thong_tin_cua_hang": "Store Information",
"Thiet_lap_mau_in": "Print Setting",
"Thiet_lap_mau_tem": "Template Setting",
"Tu_dong_in_bao_bep": "Auto Print Cook",
"Tu_dong_in_tem_khi_nhan_mon_tu_nv": "Auto Print Template From Served",
"In_sau_khi_thanh_toan": "Print After Pay",
"In_2_lien_cho_hoa_don": "Print Two For Invoice",
"In_2_lien_cho_che_bien": "Print Two For Cook",
"In_tem_truoc_thanh_toan": "Print Template Before Pay",
"Bao_che_bien_sau_thanh_toan": "Print Kitchen After Save",
"Cat_tung_mon_khi_bao_che_bien": "Print Cook Separate Menu",
"In_tam_tinh": "Allow Print Preview",
"Che_do_in_ngam": "Print Hidden Mode",
"Su_dung_2_man_hinh": "Using Two Screen",
"Chat_luong_video_man_hinh_phu": "Second Screen Video Quality",
"Hien_thanh_dieu_huong": "Show Navigation Bar",
"Giu_man_hinh_luon_sang": "Keep Screen On",
"Cai_dat_the_cung": "Card Setting",
"Nhap_so_luong_the": "Fill Card Count",
"Moi_nhap": "Please fill",
"Chieu_rong_giay": "Page Width",
"Dia_chi_IP": "IP Address",
"Link_dang_nhap": "Login link",
"Chan_trang": "Footer",
"Banner_ads_1": "Banner Ads 1",
"Banner_ads_2": "Banner Ads 2",
"Slideshow_1": "Slideshow 1",
"Slideshow_2": "Slideshow 2",
"Slideshow_3": "Slideshow 3",
"Thiet_lap_vat": "VAT Configuration",
"Gia_tri": "Value",
"Phuong_thuc_tinh": "Calculation Method",
"Khong_in": "Not Print",
"In_sunmi": "Sunmi Print",
"In_bluetooth": "Bluetooth Print",
"In_usb": "USB Print",
"In_qua_mang_lan": "Wireless Print",
"VAT_tinh_theo_tong_gia_tri_don_hang":
"VAT is calculated based on total order value",
"VAT_tinh_theo_tung_san_pham": "VAT is calculated based on each product",
"Gia_ban_da_bao_gom_VAT": "Price is including VAT",
"Tinh_nang_dang_phat_trien": "This feature is under development",
"Du_lieu_khong_hop_le": "Invalid Data",
"Vuot_qua_moc_toi_da": "Over Maximum",
"Vuot_qua_moc_toi_thieu": "Under Minimum",
"Cai_dat": "Setting",
"Ket_noi_may_in": "Printer Connection",
"Cai_dat_may_in": "Printer Configuration",
"Thiet_lap_tinh_nang": "Feature Configuration",
"Thiet_lap_he_thong": "System Configuration",
"Loi": "Error",
"Cap_nhat_that_bai": "Update Failed",
// TODO: D
'Dang_dung': 'Serving',
'Dang_trong': 'Empty',
'Danh_sach_hang_hoa': 'Product list',
'dateSale': 'Date sale',
'Don_gia': 'Unit',
'Dat_hang': 'Ordering',
'Danh_sach_don_hang': 'List invoice',
'Don_hang': 'Invoice',
'Dong_y': 'Yes',
'Den': 'To',
'Dang_ky': 'Sign up',
'Dang_nhap': 'Sign In',
'Dang_nhap_that_bai': 'Login fail',
'Dang_nhap_thanh_cong': 'Login success',
'Da_co_loi_xay_ra': 'An error has occurred',

'Du_no': "Debt",
'Diem_thuong': "Point",
'Dia_chi': 'Address',
'Du_no_VND': 'Debt(VND)',
'Don_vi_tinh_lon': 'Large unit',
'Dich_vu': 'Services',
'Don_vi_tinh_lon_va_thong_so_khac': '',
'Danh_sach_khach_hang': 'Partner',
// TODO: E

  // TODO: F
  'Quan_ly_nhan_vien': 'Employee Management',
  'Tim_kiem_nhan_vien': 'Search Employee',
  'Nhan_vien': 'Staff',
  'Quan_ly': 'Manager',
  'Khoa': 'Disable',
  'Mơ_khoa': 'Enable',
  'Vi_tri': 'Position',
  'Ten_dang_nhap': 'Username',
  'Vui_long_khong_de_trong': 'Please do not leave this field empty.',
  'Email_khong_hop_le': 'Email is invalid. Please try again!',
  'Them_moi_nhan_vien': 'Add new staff',
  'moi': 'NEW',
  'Xoa_nhan_vien': 'Delete staff',
  'Xac_nhan_xoa': 'Confirm delete',
  'Hien_thi_chi_tiet_nhan_vien': 'Show staff detail',
  'Xet_quyen_han': 'Show privileges',
  'Ha_noi': 'Hanoi',
  'HCM': 'Ho Chi Minh',
  'Nghe_an': 'Nghe An',
  'Chon_chi_nhanh': 'Please choose a branch',

// TODO: G
'Giao_dich': 'Transactions',
'gio': 'hours',
'giay': 'seconds',
'Ghi_chu': 'Note',
'Gioi_tinh': 'Gender',
'Gia_tri_quy doi': 'Conversion value',
'Gia_ban_dvt_lon': 'Price large unit',
'Gia_ban': 'Price',
'Gia_von': 'Cost',

// TODO: H
'Hang_hoa': 'Product',
'Huy': 'Cancel',
'Hoan_thanh': 'Done',
'Huy_don_hang': 'Cancel this order',
'Hien_thi_chi_tiet_don_hang': 'Detail invoice',
'Hom_qua': 'Yesterday',
'Hom_nay': 'Today',

// TODO: I
'In_lai_don_hang': 'Invoice reprint',

// TODO: K
'Khong': 'No',
'Khach_hang': 'Customer',
'Khach_le': 'Retail Customer',
'Kenh_ban_hang': 'Sell channel',
'Khong_duoc_bo_trong': 'is required',
'khac': 'Others',

// TODO: L
'Loc_theo': 'Filter with',
'login': 'logged in as @name with email @email',
'loading': 'Loading...',
'Loc_theo_nhan_vien': 'Filter by employees',
'Loc_theo_ngay': 'Filter by date',
'Loc_toan_bo_thoi_gian': 'Filter by all time',
'Luu': 'Save',
'Luu_va_sao_chep': 'Save and Coppy',
'Loc_theo_loai_hang': 'Filter by product type',
'Loc_theo_nhom_hàng': "Filter by category",

// TODO: M
'Ma_don': 'Bill code',
'Ma_chung_tu': 'Voucher code',
'Man_hinh_chinh': 'Dashboard',
'Man_hinh_thu_ngan': 'Screen for cashiers',
'Mat_khau': 'Password',
'Ma_dvt_lon': 'Price largeunit code',
'Ma_hang_hoa': "Product code",

// TODO: N
'notification': 'Notification',
'notification_content': "Notification content!",
'Ngay_tao': 'Created date',
'Ngay_ban': 'Date sale',
'Now': 'Now',
'Neu_ban_chua_co_tai_khoan': "You don't have account?",
'ngay': 'days',
'Nu': 'Female',
'Nam': 'Male',
'Nhom': 'Group',
'Ngay_sinh': "Date of birth",
'Nha_cung_cap': 'Supplier',

// TODO: O
'ok': "Ok",
'ordering': 'Ordering',

// TODO: P
'Phuong_thuc': 'Method',
'printWidth': 'Print width',
'printRevenueStatement': 'Print revenue statement',
'printProductsSold': 'Print product sold (Details)',
'Phi_van_chuyen': 'Shipping cost',
'phut': 'mins',

// TODO: Q
'Quen_mat_khau': 'Forget password?',

// TODO: R

// TODO: S
'So_luong': 'Quantity',
'shop': 'Shop',
'select': 'Select',
'settings': 'Settings',
'settingArrangeTime': 'Setting arrange time',
'So_dien_thoai': 'Phone number',

// TODO: T
'Tam_tinh': 'Provisional',
'Tong_quan': 'Dashboard',
'Thu_ngan': 'Cashier',
'Thanh_cong': 'Success',
'Tu': 'From',
'Ten': 'Name',
'Trang_thai': 'Status',
'time': 'Time',
'title': 'This is Title!',
'Tong_cong': 'Total',
'Tong_thanh_toan': 'Total payment',
'Tong_tam_tinh': 'Total provisional calculation',
'Thanh_toan': 'Pay',
'Tat_ca': 'All',
'Tim_kiem': 'Search',
'Tim_kiem_mat_hang': 'Search product',
'Tim_kiem_doi_tac': 'Search partner',
'Ten_khach_hang': 'Partner name',
'Tien_mat': 'Cash',
'Tim_kiem_don_hang': 'Search invoice',
'Tai_khoan': 'User',
'truoc': 'ago',
'Thong_bao': "Notification",
'Tinh_thanh': 'Province',
'Tong_giao_dich': "Total transaction",
'Tong_ket_cuoi_ngay': 'Revenue statement end day',
'Trang_chu': 'Main',
'Ton_kho': 'Onhand',
'Ten_hang_hoa': 'Product name',
'Ten_nhom': 'Group name',
'Thuoc_tinh': 'Properties',
'Thiet_lap_khung_gio_dac_biet': '',

// TODO: U

// TODO: V

// TODO: X
'Xac_nhan': 'Confirmation',
'Xoa': 'Delete',

// TODO: Y

// TODO: other
'7_ngay_truoc': '7 days ago',
};

