const Map<String, String> vi = {
  // TODO: A
  'Ap_dung': 'Áp dụng',
  'app_name': "POS365 VN",
  'Khong_con_ban_ghi_nao': 'Không còn bản ghi nào',

  // TODO: B
  'Ban_co_chac_huy_hoa_don': 'Bạn có chắc muốn hủy hóa đơn?',
  'Ban_co_chac_chan_muon_xoa_khach_hang': 'Bạn có chắc chắn muốn xoá khách hàng',
  'Bao_che_bien': '',

  // TODO: C
  'Chiet_khau': 'Chiết khấu',
  'Chi_nhanh': 'Chi nhánh',
  'Code': 'Mã',
  'con_trong': 'còn trống',
  'Chi_tiet_hang_hoa': 'Chi tiết hàng hoá',
  "Cho_phep_nhan_vien_thay_doi_gia": "Cho phép nhân viên thay đổi giá",
  "Cho_phep_nhan_vien_thay_doi_hang_hoa": "Cho phép thay đổi tên hàng hóa khi bán hàng?",
  "Nhan_du_lieu_tu_thu_ngan_khac": "Nhận dữ liệu từ thu ngân khác",
  "Mo_cashbox_sau_thanh_toan": "Mở Cashbox sau khi thanh toán",
  "Khong_cho_phep_ban_hang_khi_het_ton_kho": "Không cho phép bán hàng khi hết tồn kho",
  "Cai_dat_man_hinh_chon_sp": "Cài đặt màn hình chọn sản phẩm",
  "So_the_cung": "Số thẻ cứng",
  "Thiet_lap_VAT": "Thiết lập VAT",
  "Don_vi_tien_te": "Đơn vị tiền tệ",
  "Am_bao_thanh_toan": "Âm báo thanh toán",
  "Nhan_tin_nhan/thong_bao": "Nhận tin nhắn/ thông báo",
  "Thiet_lap_thanh_toan": "Thiết lập thanh toán",
  "Kich_hoat_thanh_toan_qua_QR": "Kính hoạt thanh toán qua QR",
  "In_hoa_don_truoc_khi_thanh_toan_QR": "In hoá đơn trước khi thanh toán QR",
  "Thanh_toan_VNPAY": "Thanh toán VNPAY",
  "Thanh_toan_ViettelPay": "Thanh toán ViettelPay",
  "May_in_thu_ngan": "Máy in thu ngân",
  "May_in_bao_bep_a": "Máy in báo bếp A",
  "May_in_bao_bep_b": "Máy in báo bếp B",
  "May_in_bao_bep_c": "Máy in báo bếp C",
  "May_in_bao_bep_d": "Máy in báo bếp D",
  "May_in_bao_pha_che_a": "Máy in báo pha chế A",
  "May_in_bao_pha_che_b": "Máy in báo pha chế B",
  "May_in_bao_pha_che_c": "Máy in báo pha chế C",
  "May_in_bao_pha_che_d": "Máy in báo pha chế D",
  "May_in_tem": "Máy in tem",
  "Thong_tin_cua_hang": "Thông tin cửa hàng",
  "Thiet_lap_mau_in": "Thiết lập mẫu in",
  "Thiet_lap_mau_tem": "Thiết lập mẫu tem",
  "Tu_dong_in_bao_bep": "Tự động in báo bếp",
  "Tu_dong_in_tem_khi_nhan_mon_tu_nv": "Tự động in tem khi nhận món từ nhân viên",
  "In_sau_khi_thanh_toan": "In sau khi thanh toán",
  "In_2_lien_cho_che_bien": "In 2 liên cho chế biến",
  "In_2_lien_cho_hoa_don": "In 2 liên cho hoá đơn",
  "In_tem_truoc_thanh_toan": "In tem trước thanh toán",
  "Bao_che_bien_sau_thanh_toan": "Báo chế biến sau thanh toán",
  "Cat_tung_mon_khi_bao_che_bien": "Cắt từng món khi báo chế biến",
  "In_tam_tinh": "In tạm tính",
  "Che_do_in_ngam": "Chế độ in ngầm",
  "Su_dung_2_man_hinh": "Sử dụng 2 màn hình",
  "Chat_luong_video_man_hinh_phu": "Chất lượng video màn hình phụ",
  "Hien_thanh_dieu_huong": "Hiện thanh điều hướng",
  "Giu_man_hinh_luon_sang": "Giữ màn hình luôn sáng",
  "Cai_dat_the_cung": "Cài đặt thẻ cứng",
  "Nhap_so_luong_the": "Nhập số lượng thẻ",
  "Moi_nhap": "Mời nhập",
  "Chieu_rong_giay": "Chiều rộng giấy",
  "Dia_chi_IP": "Địa chỉ IP",
  "Link_dang_nhap": "Link đăng nhập",
  "Chan_trang": "Chân trang",
  "Banner_ads_1": "Banner Ads 1",
  "Banner_ads_2": "Banner Ads 2",
  "Slideshow_1": "Slideshow 1",
  "Slideshow_2": "Slideshow 2",
  "Slideshow_3": "Slideshow 3",
  "Thiet_lap_vat": "Thiết lập VAT",
  "Gia_tri": "Giá trị",
  "Phuong_thuc_tinh": "Phương thức tính",
  "Khong_in": "Không in",
  "In_sunmi": "In Sunmi",
  "In_bluetooth": "In Bluetooth",
  "In_usb": "In USB",
  "In_qua_mang_lan": "In qua mạng LAN",
  "VAT_tinh_theo_tong_gia_tri_don_hang": "VAT tính theo tổng giá trị đơn hàng",
  "VAT_tinh_theo_tung_san_pham": "VAT tính theo từng sản phẩm",
  "Gia_ban_da_bao_gom_VAT": "Giá bán đã bao gồm VAT",
  "Tinh_nang_dang_phat_trien": "Tính năng đang phát triển",
  "Du_lieu_khong_hop_le": "Dữ liệu không hợp lệ",
  "Vuot_qua_moc_toi_da": "Vượt quá mức tối đa",
  "Vuot_qua_moc_toi_thieu": "Vượt quá mức tối thiểu",

  "Cai_dat": "Cài đặt",
  "Ket_noi_may_in": "Kết nối máy in",
  "Cai_dat_may_in": "Cài đặt máy in",
  "Thiet_lap_tinh_nang": "Thiết lập tính năng",
  "Thiet_lap_he_thong": "Thiết lập hệ thống",
  "Loi": "Lỗi",
  "Cap_nhat_that_bai": "Cập nhật thất bại",

  // TODO: D
  'Dang_dung': 'Đang dùng',
  'Dang_trong': 'Đang trống',
  'Danh_sach_hang_hoa': 'Danh sách hàng hóa',
  'dateSale': 'Ngày bán',
  'Don_gia': 'Đơn giá',
  'Dat_hang': 'Đặt hàng',
  'Danh_sach_don_hang': 'Danh sách đơn hàng',
  'Don_hang': 'Đơn hàng',
  'Dong_y': 'Đồng ý',
  'Den': 'Đến',
  'Dang_ky': 'Đăng ký',
  'Dang_nhap': 'Đăng nhập',
  'Dang_nhap_that_bai': 'Đăng nhập thất bại',
  'Dang_nhap_thanh_cong': 'Đăng nhập thành công',
  'Da_co_loi_xay_ra': 'Đã có lỗi xảy ra',
  'Danh_sach_khach_hang': 'Danh sách khách hàng',

  'Du_no': "Dư nợ",
  'Diem_thuong': "Điểm thưởng",
  'Dia_chi': 'Địa chỉ',
  'Du_no_VND': 'Dư nợ(VND)',
  'Don_vi_tinh_lon': '',
  'Dich_vu': '',
  'Don_vi_tinh_lon_va_thong_so_khac': '',
  // TODO: E

  // TODO: F
  'Quan_ly_nhan_vien': 'Quản lý nhân viên',
  'Tim_kiem_nhan_vien': 'Tìm kiếm nhân viên',
  'Nhan_vien': 'Nhân viên',
  'Quan_ly': 'Quản lý',
  'Chinh_sua': 'Chỉnh sửa',
  'Khoa': 'Khóa',
  'Mo_khoa': 'Mở khóa',
  'Vi_tri': 'Vị trí',
  'Ten_dang_nhap': 'Tên đăng nhập',
  'Vui_long_khong_de_trong': 'Vui lòng không để trống trường này.',
  'Email_khong_hop_le': 'Email không hợp lệ. Vui lòng thử lại.',
  'Them_moi_nhan_vien': 'Thêm mới nhân viên',
  'moi': 'mới',
  'Xoa_nhan_vien': 'Xóa nhân viên',
  'Xac_nhan_xoa': 'Xác nhận xóa',
  'Hien_thi_chi_tiet_nhan_vien': 'Hiển thị chi tiết nhân viên',
  'Xet_quyen_han': 'Xét quyền hạn',
  'Ha_noi': 'Hà Nội',
  'HCM': 'Hồ Chí Minh',
  'Nghe_an': 'Nghệ An',
  'Chon_chi_nhanh': 'Chọn chi nhánh',
  'button_View': 'Xem',
  'button_Add': 'Thêm mới',
  'button_Update': 'Cập nhật',
  'button_Delete': 'Xóa',
  'button_Export': 'Xuất ra file',
  'button_Import': 'Nhập từ file',
  'label_ViewCost': 'Xem giá vốn',
  'label_UpdateCost': 'Cập nhật giá vốn',
  'report_BranchProfit': 'Lợi nhuận theo chi nhánh',
  'report_CashBook': 'Sổ quỹ Thu & Chi',
  'report_COD': 'Chi phí giao hàng',
  'report_Commissionforstaffs': 'Hoa hồng nhân viên',
  'report_BestCustomers': 'Khách hàng doanh số cao',
  'report_CustomerProfit': 'Lợi nhuận theo khách hàng',
  'report_CustomerReturnProducts': 'Hàng khách trả lại',
  'report_DirectMaterialUsage': 'Hao phí nguyên liệu trực tiếp (Combo)',
  'report_EndOfDay': 'Tổng kết cuối ngày',
  'label_Point_Exchangepoints': 'Đổi điểm thưởng',
  'label_DiscountOnOrder': 'CK(HĐ)',
  'report_GrossingProducts': 'Hàng có doanh thu cao',
  'report_HighProfitsReport': 'Hàng lợi nhuận cao',
  'report_IncomeStatement': 'Kết quả kinh doanh',
  'report_Lot': 'Bảng kê Lô & Hạn sử dụng',
  'report_MaterialUsage': 'Nguyên liệu sản xuất',
  'report_MultiBranchInventoryDifference': 'Chênh lệch số lượng kiểm kê',
  'report_MultiBranchManufacturing': 'Tổng hợp thành phẩm Sản xuất/Chế biến',
  'report_MultiBranchMaterial': 'Tổng hợp sử dụng Nguyên liệu',
  'report_MultiBranchMinMax': 'Kiểm soát định mức tồn kho',
  'report_OtherTransaction': 'Giao dịch khác (hủy, tặng...)',
  'report_ProductPurchaseDetailReport': 'Chi tiết hàng nhập kho',
  'report_MultiBranchProductSold': 'Tổng hợp hàng bán ra',
  'report_PreOrder': 'Tổng hợp hàng khách đặt mua',
  'report_MultiBranchPriceDifference': 'Kiểm soát chênh lệch giá bán',
  'report_MultiBranchProductPurchase': 'Tổng hợp hàng nhập kho',
  'report_MultiBranchReturnToSupplier': 'Tổng hợp hàng trả Nhà Cung Cấp',
  'report_RevenueByBranch': 'Doanh thu theo chi nhánh',
  'report_MultiBranchSale': 'Phân tích tần suất bán hàng',
  'report_MultiBranchSalesEffectiveness': 'Hiệu quả bán hàng',
  'report_MultiBranchSalesFrequency': 'Tần suất bán theo mặt hàng',
  'report_MultiBranchTransfer': 'Tổng hợp luân chuyển hàng',
  'report_OrderProfit': 'Lợi nhuận theo đơn hàng',
  'report_PaymentMethods': 'Phương thức thanh toán',
  'report_PriceDifference': 'Chênh lệch giá bán',
  'report_ProducInOutStock': 'Xuất - Nhập - Tồn',
  'label_Product_Popular': 'Hàng bán chạy',
  'report_ProductProfitByBranch': 'Lợi nhuận hàng theo chi nhánh',
  'report_ProductProfit': 'Lợi nhuận hàng bán',
  'report_ProductsSoldByBranch': 'Hàng bán theo chi nhánh',
  'report_ProductSaleByKitchenReport': 'Hàng bán theo bếp chế biến',
  'report_ProductsSoldByPartner': 'Hàng bán theo khách',
  'report_ProductSaleByRoomReport': 'Hàng bán theo Phòng/Bàn',
  'report_ProductReturnByUser': 'Hàng trả lại theo nhân viên',
  'report_ProductsSoldByUser': 'Hàng bán theo nhân viên',
  'report_ProductSaleDetail': 'Hàng hóa bán ra (Chi tiết)',
  'report_ProductsSold': 'Hàng hóa bán ra',
  'report_ProductsReturnedToSuppliers': 'Hàng trả Nhà cung cấp',
  'report_PurchaseDetailReport': 'Tổng hợp phiếu nhập hàng',
  'report_Reserve': 'Kế hoạch dự trù nhập hàng',
  'report_ReturnToCustomerDetail': 'Tổng hợp phiếu khách trả hàng',
  'report_ReturnToSupplierDetail': 'Tổng hợp đơn trả nhà cung cấp',
  'report_RevenueByCustomers': 'Doanh thu theo khách hàng',
  'report_RevenueByUsers': 'Doanh thu theo nhân viên',
  'report_RevenueDetail': 'Chi tiết doanh thu',
  'report_SlowSellingProducts': 'Hàng bán chậm',
  'report_StockOrderByPartner': 'Báo cáo tổng hợp hàng nhập theo nhà cung cấp',
  'report_StockOrderDetail': 'Báo cáo tổng hợp hàng nhập',
  'report_Summaryofreceivable': 'Tổng hợp công nợ phải thu',
  'report_Summaryofpayable': 'Tổng hợp công nợ phải trả',
  'report_UnmarketableProducts': 'Hàng không bán được',
  'report_VATSummary': 'Tổng hợp VAT',
  'report_WarehousesValues': 'Giá trị kho hàng',
  'label_Permission_AccountingTransaction': 'Thu & Chi',
  'label_Permission_DeliveryOrder': 'Giao hàng - COD',
  'label_Permission_Branch': 'Quản lý chi nhánh',
  'label_Permission_InventoryCount': 'Kiểm kê',
  'label_Permission_Manufacturing': 'Sản xuất & Sơ chế',
  'label_Permission_Order': 'Bán hàng',
  'label_Permission_OrderChannel': 'Kênh bán hàng',
  'label_Permission_OtherTransaction': 'Giao dịch khác (hủy, tặng...)',
  'label_Permission_Partner': 'Quản lý đối tác',
  'label_Permission_Product': 'Quản lý hàng hóa',
  'label_Permission_PurchaseOrder': 'Nhập hàng',
  'label_Permission_PurchaseOrderReturn': 'Trả hàng nhà cung cấp',
  'label_Permission_Return': 'Trả hàng',
  'label_Permission_Sm': 'Gửi tin Sms',
  'label_Permission_Transfer': 'Chuyển hàng nội bộ',
  'label_Permission_User': 'Quản lý nhân viên',
  'label_Permission_PosParameter': 'Thiết lập tính năng',
  'label_Permission_PriceBook': 'Thiết lập bảng giá',
  'label_Permission_PrintTemplate': 'Thiết lập mẫu in',
  'label_Permission_Room': 'Quản lý danh sách Phòng/Bàn',
  'label_Permission_Voucher': 'Voucher',
  'label_Permission_Report': 'Báo cáo',


  // TODO: G
  'Giao_dich': 'Giao dịch',
  'gio': 'giờ',
  'giay': 'giây',
  'Ghi_chu': 'Ghi chú',
  'Gioi_tinh': 'Giới tính',
  'Gia_tri_quy_doi': '',
  'Gia_ban_dvt_lon': '',

  // TODO: H
  'Hang_hoa': 'Hàng hóa',
  'Huy': "Huỷ",
  'Hoan_thanh': 'Hoàn thành',
  'Hien_thi_chi_tiet_don_hang': 'Hiển thị chi tiêt đơn hàng',
  'Huy_don_hang': 'Hủy đơn hàng',
  'Hom_qua': 'Hôm qua',
  'Hom_nay': 'Hôm nay',
  'Thiet_lap_extra_topping': 'Thiết lập extra/topping',
  'Tim_kiem_san_pham': 'Tìm kiếm sản phẩm',
  'Hien_thi_chi_tiet_san_pham': 'Hiển thị chi tiết sản phẩm',
  'Mien_phi': 'Miễn phí',
  'Cap_nhat_extra_topping': 'Cập nhật Extra/Topping',
  'Ten_extra_topping': 'Tên Extra/Topping',
  'Ten_nhom': 'Tên nhóm',
  'So_luong_tru_kho': 'Số lượng trừ kho khi bán 1 đơn vị',
  'Gia_ban': 'Giá bán',

  // TODO: I
  'In_lai_don_hang': 'In lại đơn hàng',

  // TODO: K
  'khac': 'Khác',
  'Khong': 'Không',
  'Khach_hang': 'Khách hàng',
  'Khach_le': 'Khách lẻ',
  'Kenh_ban_hang': 'Kênh bán hàng',
  'Khong_duoc_bo_trong': 'không được bỏ trống',

  // TODO: L
  'Loc_theo': 'Lọc theo',
  'login': 'Đăng nhập user @name，email @email',
  'loading': 'Đang tải...',
  'Loc_theo_nhan_vien': 'Lọc theo nhân viên',
  'Loc_theo_ngay': 'Lọc theo ngày',
  'Loc_toan_bo_thoi_gian': 'Toàn bộ thời gian',
  'Luu': 'Lưu',
  'Luu_va_sao_chep': '',

  // TODO: M
  'Ma_don': 'Mã đơn',
  'Ma_chung_tu': 'Mã chứng từ',
  'Man_hinh_chinh': 'Màn hình chính',
  'Man_hinh_thu_ngan': 'Màn hình thu ngân',
  'Mat_khau': 'Mật khẩu',
  'Ma_dvt_lon': '',

  // TODO: N
  'notification': 'Thông báo',
  'notification_content': "Nội dung thông báo!",
  'Ngay_tao': 'Ngày tạo',
  'Ngay_ban': 'Ngày bán',
  'Now': 'Hiện tại',
  'Neu_ban_chua_co_tai_khoan': "Nếu bạn chưa có tài khoản?",
  'ngay': 'ngày',
  'Nu': 'Nữ',
  'Nam': 'Nam',
  'Nhom': 'Nhóm',
  'Ngay_sinh': "Ngày sinh",

  // TODO: O
  'ok': "Đồng ý",

  // TODO: P
  'Phuong_thuc': 'Phương thức',
  'Phi_van_chuyen': 'Phí vận chuyển',
  'printWidth': 'Chiều rộng khổ in',
  'printRevenueStatement': 'In báo cáo',
  'printProductsSold': 'In hàng hóa bán ra (Chi tiết)',
  'pay': 'Thanh toán',
  'phut': 'phút',

  // TODO: Q
  'Quen_mat_khau': 'Quên mật khẩu?',

  // TODO: R

  // TODO: S
  'So_luong': 'Số lượng',
  'shop': 'Cửa hàng',
  'select': 'Lựa chọn',
  'settings': 'Thiết lập',
  'settingArrangeTime': 'Thiết lập khung thời gian',
  'So_dien_thoai': 'Số điện thoại',

  // TODO: T
  'Tam_tinh': 'Tạm tính',
  'Tong_quan': 'Tổng quan',
  'Thu_ngan': 'Thu ngân',
  'Thanh_cong': 'Thành công',
  'Tu': 'Từ',
  'Ten': 'Tên',
  'Trang_thai': 'Trạng thái',
  'title': 'Tiêu đề',
  'time': 'Thời gian',
  'Tong_cong': 'Tổng cộng',
  'Tong_thanh_toan': 'Tổng thanh toán',
  'Tong_tam_tinh': 'Tổng tạm tính',
  'Thanh_toan': 'Thanh toán',
  'Tat_ca': 'Tất cả',
  'Tim_kiem': 'Tìm kiếm',
  'Tim_kiem_mat_hang': 'Tìm kiếm mặt hàng',
  'Tim_kiem_doi_tac': 'Tìm kiếm đối tác',
  'Ten_khach_hang': 'Tên khách hàng',
  'Tien_mat': 'Tiền mặt',
  'Tim_kiem_don_hang': 'Tìm kiếm đơn hàng',
  'Tai_khoan': 'Tài khoản',
  'truoc': 'trước',
  'Thong_bao': "Thông báo",
  'Tinh_thanh': 'Tỉnh thành',
  'Tong_giao_dich': "Tổng giao dịch",
  'Tong_ket_cuoi_ngay': 'Tổng kết cuối ngày',
  'Trang_chu': 'Trang chủ',
  'Ton_kho': '',
  'Thiet_lap_khung_gio_dac_biet': '',

  // TODO: U

  // TODO: V

  // TODO: X
  'Xac_nhan': 'Xác nhận',
  'Xoa': 'Xoá',

  // TODO: Y

  // TODO: other
  '7_ngay_truoc': '7 ngày trước',
};
